lauren-app/config/routes.rb
Rails.application.routes.draw do
  resources :favorite_toys
  resources :dogs
  resources :humen
  resources :users

  root 'sessions#new'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', :as => 'logout'

end

lauren-app/app/models/favorite_toy.rb
class FavoriteToy
  include Mongoid::Document

  embedded_in :dog

  field :name, type: String
  field :type, type: String
end

lauren-app/app/controllers/favorite_toys_controller.rb
class FavoriteToysController < ApplicationController
  before_action :set_favorite_toy, only: [:show, :edit, :update, :destroy]

  # GET /favorite_toys
  # GET /favorite_toys.json
  def index
    @favorite_toys = FavoriteToy.all
  end

  # GET /favorite_toys/1
  # GET /favorite_toys/1.json
  def show
  end

  # GET /favorite_toys/new
  def new
    @favorite_toy = FavoriteToy.new
  end

  # GET /favorite_toys/1/edit
  def edit
  end

  # POST /favorite_toys
  # POST /favorite_toys.json
  def create
    @favorite_toy = FavoriteToy.new(favorite_toy_params)

    respond_to do |format|
      if @favorite_toy.save
        format.html { redirect_to @favorite_toy, notice: 'Favorite toy was successfully created.' }
        format.json { render :show, status: :created, location: @favorite_toy }
      else
        format.html { render :new }
        format.json { render json: @favorite_toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_toys/1
  # PATCH/PUT /favorite_toys/1.json
  def update
    respond_to do |format|
      if @favorite_toy.update(favorite_toy_params)
        format.html { redirect_to @favorite_toy, notice: 'Favorite toy was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite_toy }
      else
        format.html { render :edit }
        format.json { render json: @favorite_toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_toys/1
  # DELETE /favorite_toys/1.json
  def destroy
    @favorite_toy.destroy
    respond_to do |format|
      format.html { redirect_to favorite_toys_url, notice: 'Favorite toy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_toy
      @favorite_toy = FavoriteToy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_toy_params
      params.require(:favorite_toy).permit(:name, :type)
    end
end

lauren-app/app/helpers/favorite_toys_helper.rb
module FavoriteToysHelper
end

lauren-app/app/views/favorite_toys/_form.html.erb
<%= form_for(@favorite_toy) do |f| %>
  <% if @favorite_toy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_toy.errors.count, "error") %> prohibited this favorite_toy from being saved:</h2>

      <ul>
      <% @favorite_toy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lauren-app/app/views/favorite_toys/edit.html.erb
<h1>Editing Favorite Toy</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite_toy %> |
<%= link_to 'Back', favorite_toys_path %>

lauren-app/app/views/favorite_toys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Favorite Toys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_toys.each do |favorite_toy| %>
      <tr>
        <td><%= favorite_toy.name %></td>
        <td><%= favorite_toy.type %></td>
        <td><%= link_to 'Show', favorite_toy %></td>
        <td><%= link_to 'Edit', edit_favorite_toy_path(favorite_toy) %></td>
        <td><%= link_to 'Destroy', favorite_toy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite toy', new_favorite_toy_path %>

lauren-app/app/views/favorite_toys/new.html.erb
<h1>New Favorite Toy</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_toys_path %>

lauren-app/app/views/favorite_toys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @favorite_toy.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @favorite_toy.type %>
</p>

<%= link_to 'Edit', edit_favorite_toy_path(@favorite_toy) %> |
<%= link_to 'Back', favorite_toys_path %>