lauren-app/config/routes.rb
Rails.application.routes.draw do
  resources :favorite_toys
  resources :dogs
  resources :humen
  resources :users

  root 'sessions#new'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', :as => 'logout'

end

lauren-app/app/controllers/humen_controller.rb
class HumenController < ApplicationController
  before_action :set_human, only: [:show, :edit, :update, :destroy]

  # GET /humen
  # GET /humen.json
  def index
    @humen = Human.all
  end

  # GET /humen/1
  # GET /humen/1.json
  def show
  end

  # GET /humen/new
  def new
    @human = Human.new
  end

  # GET /humen/1/edit
  def edit
  end

  # POST /humen
  # POST /humen.json
  def create
    @human = Human.new(human_params)

    respond_to do |format|
      if @human.save
        format.html { redirect_to @human, notice: 'Human was successfully created.' }
        format.json { render :show, status: :created, location: @human }
      else
        format.html { render :new }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /humen/1
  # PATCH/PUT /humen/1.json
  def update
    respond_to do |format|
      if @human.update(human_params)
        format.html { redirect_to @human, notice: 'Human was successfully updated.' }
        format.json { render :show, status: :ok, location: @human }
      else
        format.html { render :edit }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humen/1
  # DELETE /humen/1.json
  def destroy
    @human.destroy
    respond_to do |format|
      format.html { redirect_to humen_url, notice: 'Human was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_human
      @human = Human.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def human_params
      params.require(:human).permit(:name, :numOfDogs)
    end
end

lauren-app/app/helpers/humen_helper.rb
module HumenHelper
end

lauren-app/app/views/humen/_form.html.erb
<%= form_for(@human) do |f| %>
  <% if @human.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@human.errors.count, "error") %> prohibited this human from being saved:</h2>

      <ul>
      <% @human.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :numOfDogs %><br>
    <%= f.number_field :numOfDogs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lauren-app/app/views/humen/edit.html.erb
<h1>Editing Human</h1>

<%= render 'form' %>

<%= link_to 'Show', @human %> |
<%= link_to 'Back', humen_path %>

lauren-app/app/views/humen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Humen</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Numofdogs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @humen.each do |human| %>
      <tr>
        <td><%= human.name %></td>
        <td><%= human.numOfDogs %></td>
        <td><%= link_to 'Show', human %></td>
        <td><%= link_to 'Edit', edit_human_path(human) %></td>
        <td><%= link_to 'Destroy', human, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Human', new_human_path %>

lauren-app/app/views/humen/new.html.erb
<h1>New Human</h1>

<%= render 'form' %>

<%= link_to 'Back', humen_path %>

lauren-app/app/views/humen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @human.name %>
</p>

<p>
  <strong>Numofdogs:</strong>
  <%= @human.numOfDogs %>
</p>

<%= link_to 'Edit', edit_human_path(@human) %> |
<%= link_to 'Back', humen_path %>